name: Android CI Workflow  # This is the name you will see in the GitHub Actions tab

on:
  push:
    branches:
      - main  # Run CI when pushing to the main branch
  pull_request:
    branches:
      - main  # Run CI when PR is made toward the main branch

jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest  # Use Ubuntu runner (a Linux machine on GitHub's cloud)

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        # Downloads your project code into the runner so the workflow can use it

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        # Android Gradle plugin requires Java 17

      - name: Give Gradle permissions
        run: chmod +x ./gradlew
        # Make the Gradle wrapper executable on Linux

      - name: Build the app
        run: ./gradlew assembleDebug
        # Builds the debug APK

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
        # Stores the APK so you can download it from GitHub after build